controllers_project:
  resource: ../../src/Controller/
  type: annotation

controllers_user_bundle:
  resource: ../../src/Controller
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation
